server:
  port: 8085
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root
    password: 123456
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create