server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root
    password: 123456
jpa:
  database: mysql
  show-sql: true
  hibernate:
      dll-auto: create
